version: "3.9"

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres_employee_db
    environment:
      POSTGRES_DB: employee_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "5432:5432"
    volumes:
      - employee_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d employee_management"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - employee_management_net

volumes:
  employee_postgres_data:

networks:
  employee_management_net:
    name: employee_management_net
